import img1 from "../assets/images/img1.png";
import img2 from "../assets/images/img2.png";
import img3 from "../assets/images/img3.png";
import calender from "../assets/images/calender.svg";
import location from "../assets/images/location.svg";
import share from "../assets/images/share.svg";

const data = [
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img1,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img2,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img3,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img1,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img3,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img1,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img2,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img1,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img3,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img2,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img1,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img3,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img3,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img1,
    },
    {
      title: "Energy Next 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "ICC Sydney, Darling Harbour, Australia",
      image: img2,
    },
    {
      title: "Convention for Solar Enterprises",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "Virtual",
      image: img1,
    },
    {
      title: "Annual International Sustainability Conference, 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "Dean Carter University, Illinois, USA",
      image: img3,
    },
    {
      title: "Annual International Sustainability Conference, 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "Dean Carter University, Illinois, USA",
      image: img1,
    },
    {
      title: "Annual International Sustainability Conference, 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "Dean Carter University, Illinois, USA",
      image: img3,
    },
    {
      title: "Annual International Sustainability Conference, 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "Dean Carter University, Illinois, USA",
      image: img3,
    },
    {
      title: "Annual International Sustainability Conference, 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "Dean Carter University, Illinois, USA",
      image: img1,
    },
    {
      title: "Annual International Sustainability Conference, 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "Dean Carter University, Illinois, USA",
      image: img1,
    },
    {
      title: "Annual International Sustainability Conference, 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "Dean Carter University, Illinois, USA",
      image: img3,
    },
    {
      title: "Annual International Sustainability Conference, 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "Dean Carter University, Illinois, USA",
      image: img1,
    },
    {
      title: "Annual International Sustainability Conference, 2023",
      calenderIcon: calender,
      locationIcon: location,
      shareIcon: share,
      date: "12/12/2021",
      time: "12:00 PM",
      location: "Dean Carter University, Illinois, USA",
      image: img3,
    }    
  ];

export default data