import adobe from "../assets/icons/adobe.png";
import amazon from "../assets/icons/Amazon.svg";
import adidas from "../assets/icons/adidas.png";

const report = [
    {
      company: "DANSKE.TH",
      companyType : "technology",
      logo: adobe,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "ADSK",
      companyType : "technology",
      logo: amazon,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "BLK",
      companyType : "technology",
      logo: adidas,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "DANSKE.TH",
      companyType : "technology",
      logo: adobe,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "ADSK",
      companyType : "technology",
      logo: amazon,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "BLK",
      companyType : "technology",
      logo: adidas,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "DANSKE.TH",
      companyType : "technology",
      logo: adobe,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "ADSK",
      companyType : "technology",
      logo: amazon,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "BLK",
      companyType : "technology",
      logo: adidas,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "BLK",
      companyType : "technology",
      logo: adidas,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "DANSKE.TH",
      companyType : "technology",
      logo: adobe,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "ADSK",
      companyType : "technology",
      logo: amazon,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "BLK",
      companyType : "technology",
      logo: adidas,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "DANSKE.TH",
      companyType : "technology",
      logo: adobe,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "ADSK",
      companyType : "technology",
      logo: amazon,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "BLK",
      companyType : "technology",
      logo: adidas,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "DANSKE.TH",
      companyType : "technology",
      logo: adobe,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "ADSK",
      companyType : "technology",
      logo: amazon,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "BLK",
      companyType : "technology",
      logo: adidas,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
    {
      company: "BLK",
      companyType : "technology",
      logo: adidas,
      gri: true,
      sasb: false,
      cdp: true,
      tcfd: false,
    },
  ];

export default report