export {default as Header} from "./Header/Header"
export {default as Footer} from "./Footer/Footer"
export {default as HomeArticles} from "./HomeArticles/HomeArticles"
export {default as HomeLatest} from "./HomeLatest/HomeLatest"
export {default as HomeUpcoming} from "./HomeUpcoming/HomeUpcoming"
export {default as SubscriberSec} from "./SubscriberSec/SubscriberSec"
export {default as EventDetailPage} from "./EventDetailPage/EventDetailPage"
export {default as GlossaryCard} from "./GlossaryCard/GlossaryCard"
export {default as NewsLetter} from "./Newsletter/NewsLetter"
export {default as Search} from "./Search/Search"
export {default as SearchArticleCard} from "./SearchArticleCard/SArticleCard"
export {default as SearchPopularCard} from "./SearchPopularCard/SPopularCard"
export { default as About } from "./About/AboutPage"
export { default as CompaniePage } from "./Companies/CompaniePage"
export { default as Terms } from "./Terms/Terms"
export { default as UpcomingCard} from "./UpComingCard/UpcomingCard"

